name: NutriWise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/profile.jpg
    - assets/apple.jpg
    - assets/salad.jpg
    - assets/soup.jpg
    - assets/pumpkin.jpg
    - assets/hot_chocolate.jpg
    - assets/logo.png
    - assets/login_bg.jpg
    # Categories
    - assets/categories/Beverages/beverages.jpg
    - assets/categories/Snacks/snacks.jpg
    - assets/categories/Dairy/dairy.jpg
    - assets/categories/Staples/staples.jpg
    - assets/categories/Canned/canned.jpg
    - assets/categories/Spices/spices.jpg
    # Category 1: Beverages (Coffee)
    - assets/categories/Beverages/Coffee/Basilio_Coffee.jpg
    - assets/categories/Beverages/Coffee/SGD_Coffee.png
    - assets/categories/Beverages/Coffee/Bos_Coffee.png
    # Category 1: Beverages (Green Tea)
    - assets/categories/Beverages/Green_Tea/Yogi_Green_Tea.jpg
    - assets/categories/Beverages/Green_Tea/Twinings_Green_Tea.png
    - assets/categories/Beverages/Green_Tea/Lipton_Matcha.jpg
    # Category 1: Beverages (Orange Juice)
    - assets/categories/Beverages/Orange_Juice/Tropicana_Pure.jpg
    - assets/categories/Beverages/Orange_Juice/Floridas_Natural.jpg
    - assets/categories/Beverages/Orange_Juice/Locally_Blended.jpg
    # Category 1: Beverages (Sparkling Water)
    - assets/categories/Beverages/Sparkling_Water/San_Pellegrino.jpg
    - assets/categories/Beverages/Sparkling_Water/Perrier.jpg
    - assets/categories/Beverages/Sparkling_Water/Natures_Spring.jpg
    # Category 1: Beverages (Almond Milk)
    - assets/categories/Beverages/Almond_Milk/Alpro_Almond_Milk.jpg
    - assets/categories/Beverages/Almond_Milk/Pacific_Foods.jpg
    - assets/categories/Beverages/Almond_Milk/Almond_Breeze.jpg

    # Category 2: Snacks (Pretzels)
    - assets/categories/Snacks/Pretzels/Annies_Organic_Pretzel_Bunnies.jpg
    - assets/categories/Snacks/Pretzels/Synders_Pretzel.jpg
    - assets/categories/Snacks/Pretzels/Trader_Joes_Honey_Wheat_Pretzels.jpg
    # Category 2: Snacks (Trail Mix)
    - assets/categories/Snacks/Trail_Mix/Take_Root_Banana_Cacao_Trail_Mix.jpg
    - assets/categories/Snacks/Trail_Mix/Nuts_&_Glory_Trail_Mix.png
    - assets/categories/Snacks/Trail_Mix/Trophy_Farms_Trail_Mix.jpg
    # Category 2: Snacks (Granola Bars)
    - assets/categories/Snacks/Granola_Bars/Kind_Bars.jpg
    - assets/categories/Snacks/Granola_Bars/Nature_Valley_Crunchy_Granola_Bars.jpg
    - assets/categories/Snacks/Granola_Bars/Take_Root_Energy_Bars.jpg
    # Category 2: Snacks (Popcorn)
    - assets/categories/Snacks/Popcorn/Boom_Chicka_Pop.jpg
    - assets/categories/Snacks/Popcorn/Lesser_Evil_Himalayan_Pink_Salt_Popcorn.jpg
    - assets/categories/Snacks/Popcorn/Skinny_Pop_Original.jpg
    # Category 2: Snacks (Dark Chocolate)
    - assets/categories/Snacks/Dark_Chocolate/Theo_Organic_85%_Dark_Chocolate.jpg
    - assets/categories/Snacks/Dark_Chocolate/Risa_Chocolates.jpg
    - assets/categories/Snacks/Dark_Chocolate/Malagos_Dark_Chocolate.jpg

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
