name: NutriWise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/profile.jpg
    - assets/apple.jpg
    - assets/salad.jpg
    - assets/soup.jpg
    - assets/pumpkin.jpg
    - assets/hot_chocolate.jpg
    - assets/logo.png
    - assets/login_bg.jpg
    # Categories
    - assets/categories/dietary.png
    - assets/categories/health.jpg
    - assets/categories/meal.png
    - assets/categories/ingredients.png
    - assets/categories/beverages.png
    - assets/categories/pantry.png

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
